import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import java.sql.*;
import javax.swing.*;
import java.awt.*;
import javax.swing.table.DefaultTableModel;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author fola
 */
public class lab_loggedin_page extends javax.swing.JFrame {

    /**
     * Creates new form user_loggedin_page
     */
     Connection conn = null;
    Statement stmt = null;
    ResultSet rs = null;
    PreparedStatement st = null;
    private String path;
    private String s;
    
    public lab_loggedin_page() {
       super("Edit Criminal info");
        conn = dbaseConnx.openConnection();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        title_banner = new javax.swing.JLabel();
        cha_test_frame = new javax.swing.JInternalFrame();
        jPanel9 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        change_cha_test = new javax.swing.JButton();
        phone_label14 = new javax.swing.JLabel();
        nd_cha_test = new javax.swing.JTextField();
        search_cha_test = new javax.swing.JButton();
        username_label10 = new javax.swing.JLabel();
        cd_cha_test = new javax.swing.JTextField();
        cc_cha_test = new javax.swing.JTextField();
        phone_label11 = new javax.swing.JLabel();
        labid_cha_test = new javax.swing.JTextField();
        password_label5 = new javax.swing.JLabel();
        exit5 = new javax.swing.JButton();
        username_label11 = new javax.swing.JLabel();
        bg6 = new javax.swing.JLabel();
        action_window6 = new javax.swing.JLabel();
        cha_vac_frame = new javax.swing.JInternalFrame();
        jPanel11 = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        change_cha_test2 = new javax.swing.JButton();
        phone_label15 = new javax.swing.JLabel();
        nd_cha_vac = new javax.swing.JTextField();
        search_cha_test2 = new javax.swing.JButton();
        username_label14 = new javax.swing.JLabel();
        cd_cha_vac = new javax.swing.JTextField();
        cc_cha_vac = new javax.swing.JTextField();
        phone_label13 = new javax.swing.JLabel();
        labid_cha_vac = new javax.swing.JTextField();
        password_label7 = new javax.swing.JLabel();
        exit7 = new javax.swing.JButton();
        username_label15 = new javax.swing.JLabel();
        bg8 = new javax.swing.JLabel();
        action_window8 = new javax.swing.JLabel();
        bottom_banner = new javax.swing.JLabel();
        action_window = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();
        covid_mgmnt_menu = new javax.swing.JMenuBar();
        testing_menu = new javax.swing.JMenu();
        cha_test = new javax.swing.JMenuItem();
        vaccination_menu = new javax.swing.JMenu();
        cha_vac = new javax.swing.JMenuItem();
        title_screen_menu = new javax.swing.JMenu();
        sign_out_menu = new javax.swing.JMenu();
        exit_menu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Welcome to Covid Manager ");

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title_banner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/title_banner.png"))); // NOI18N
        jPanel3.add(title_banner, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1140, -1));

        cha_test_frame.setTitle("Update Test Results");
        cha_test_frame.setVisible(false);

        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel9.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, 680, 20));

        change_cha_test.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        change_cha_test.setForeground(new java.awt.Color(46, 56, 80));
        change_cha_test.setText("UPDATE");
        change_cha_test.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                change_cha_testActionPerformed(evt);
            }
        });
        jPanel9.add(change_cha_test, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 400, 130, 40));

        phone_label14.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        phone_label14.setForeground(new java.awt.Color(46, 56, 80));
        phone_label14.setText("Updated Result :");
        jPanel9.add(phone_label14, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, 200, 50));

        nd_cha_test.setBackground(new java.awt.Color(242, 242, 242));
        nd_cha_test.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        nd_cha_test.setForeground(new java.awt.Color(46, 56, 80));
        nd_cha_test.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nd_cha_test.setToolTipText("Please enter correct Username");
        nd_cha_test.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        nd_cha_test.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nd_cha_testActionPerformed(evt);
            }
        });
        jPanel9.add(nd_cha_test, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 370, 370, 40));

        search_cha_test.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        search_cha_test.setForeground(new java.awt.Color(46, 56, 80));
        search_cha_test.setText("SEARCH");
        search_cha_test.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_cha_testActionPerformed(evt);
            }
        });
        jPanel9.add(search_cha_test, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, 130, 40));

        username_label10.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        username_label10.setForeground(new java.awt.Color(46, 56, 80));
        username_label10.setText("Update Test Results Here,");
        jPanel9.add(username_label10, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 340, 50));

        cd_cha_test.setEditable(false);
        cd_cha_test.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        cd_cha_test.setForeground(new java.awt.Color(46, 56, 80));
        cd_cha_test.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cd_cha_test.setToolTipText("Please enter correct Username");
        cd_cha_test.setBorder(null);
        cd_cha_test.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cd_cha_testActionPerformed(evt);
            }
        });
        jPanel9.add(cd_cha_test, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 270, 330, 40));

        cc_cha_test.setEditable(false);
        cc_cha_test.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        cc_cha_test.setForeground(new java.awt.Color(46, 56, 80));
        cc_cha_test.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cc_cha_test.setToolTipText("Please enter correct Username");
        cc_cha_test.setBorder(null);
        cc_cha_test.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cc_cha_testActionPerformed(evt);
            }
        });
        jPanel9.add(cc_cha_test, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 210, 370, 40));

        phone_label11.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        phone_label11.setForeground(new java.awt.Color(46, 56, 80));
        phone_label11.setText("Current Status of Result:");
        jPanel9.add(phone_label11, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 270, 50));

        labid_cha_test.setBackground(new java.awt.Color(242, 242, 242));
        labid_cha_test.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        labid_cha_test.setForeground(new java.awt.Color(46, 56, 80));
        labid_cha_test.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        labid_cha_test.setToolTipText("Please enter correct Username");
        labid_cha_test.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        labid_cha_test.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                labid_cha_testActionPerformed(evt);
            }
        });
        jPanel9.add(labid_cha_test, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, 370, 40));

        password_label5.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        password_label5.setForeground(new java.awt.Color(46, 56, 80));
        password_label5.setText("Current Lab Area:");
        jPanel9.add(password_label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 190, 50));

        exit5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.jpg"))); // NOI18N
        exit5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit5ActionPerformed(evt);
            }
        });
        jPanel9.add(exit5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 10, 30, 30));

        username_label11.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        username_label11.setForeground(new java.awt.Color(46, 56, 80));
        username_label11.setText("Lab ID:");
        jPanel9.add(username_label11, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 130, 50));

        bg6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bg.png"))); // NOI18N
        jPanel9.add(bg6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 680, 430));

        action_window6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bgWHITE.png"))); // NOI18N
        jPanel9.add(action_window6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1130, 510));

        javax.swing.GroupLayout cha_test_frameLayout = new javax.swing.GroupLayout(cha_test_frame.getContentPane());
        cha_test_frame.getContentPane().setLayout(cha_test_frameLayout);
        cha_test_frameLayout.setHorizontalGroup(
            cha_test_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        cha_test_frameLayout.setVerticalGroup(
            cha_test_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.add(cha_test_frame, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1140, 540));

        cha_vac_frame.setTitle("Issue Certificate");
        cha_vac_frame.setVisible(false);

        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel11.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, 680, 20));

        change_cha_test2.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        change_cha_test2.setForeground(new java.awt.Color(46, 56, 80));
        change_cha_test2.setText("UPLOAD");
        change_cha_test2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                change_cha_test2ActionPerformed(evt);
            }
        });
        jPanel11.add(change_cha_test2, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 400, 130, 40));

        phone_label15.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        phone_label15.setForeground(new java.awt.Color(46, 56, 80));
        phone_label15.setText("Updated Result :");
        jPanel11.add(phone_label15, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, 200, 50));

        nd_cha_vac.setBackground(new java.awt.Color(242, 242, 242));
        nd_cha_vac.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        nd_cha_vac.setForeground(new java.awt.Color(46, 56, 80));
        nd_cha_vac.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nd_cha_vac.setToolTipText("Please enter correct Username");
        nd_cha_vac.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        nd_cha_vac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nd_cha_vacActionPerformed(evt);
            }
        });
        jPanel11.add(nd_cha_vac, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 370, 370, 40));

        search_cha_test2.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        search_cha_test2.setForeground(new java.awt.Color(46, 56, 80));
        search_cha_test2.setText("SEARCH");
        search_cha_test2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_cha_test2ActionPerformed(evt);
            }
        });
        jPanel11.add(search_cha_test2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, 130, 40));

        username_label14.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        username_label14.setForeground(new java.awt.Color(46, 56, 80));
        username_label14.setText("Certify for Fully Vaccinated,");
        jPanel11.add(username_label14, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 340, 50));

        cd_cha_vac.setEditable(false);
        cd_cha_vac.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        cd_cha_vac.setForeground(new java.awt.Color(46, 56, 80));
        cd_cha_vac.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cd_cha_vac.setToolTipText("Please enter correct Username");
        cd_cha_vac.setBorder(null);
        cd_cha_vac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cd_cha_vacActionPerformed(evt);
            }
        });
        jPanel11.add(cd_cha_vac, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 270, 330, 40));

        cc_cha_vac.setEditable(false);
        cc_cha_vac.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        cc_cha_vac.setForeground(new java.awt.Color(46, 56, 80));
        cc_cha_vac.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cc_cha_vac.setToolTipText("Please enter correct Username");
        cc_cha_vac.setBorder(null);
        cc_cha_vac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cc_cha_vacActionPerformed(evt);
            }
        });
        jPanel11.add(cc_cha_vac, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 210, 370, 40));

        phone_label13.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        phone_label13.setForeground(new java.awt.Color(46, 56, 80));
        phone_label13.setText("Current Status of Result:");
        jPanel11.add(phone_label13, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 270, 50));

        labid_cha_vac.setBackground(new java.awt.Color(242, 242, 242));
        labid_cha_vac.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        labid_cha_vac.setForeground(new java.awt.Color(46, 56, 80));
        labid_cha_vac.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        labid_cha_vac.setToolTipText("Please enter correct Username");
        labid_cha_vac.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        labid_cha_vac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                labid_cha_vacActionPerformed(evt);
            }
        });
        jPanel11.add(labid_cha_vac, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, 370, 40));

        password_label7.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        password_label7.setForeground(new java.awt.Color(46, 56, 80));
        password_label7.setText("Current Lab Area:");
        jPanel11.add(password_label7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 190, 50));

        exit7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.jpg"))); // NOI18N
        exit7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit7ActionPerformed(evt);
            }
        });
        jPanel11.add(exit7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 10, 30, 30));

        username_label15.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        username_label15.setForeground(new java.awt.Color(46, 56, 80));
        username_label15.setText("Lab ID:");
        jPanel11.add(username_label15, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 130, 50));

        bg8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bg.png"))); // NOI18N
        jPanel11.add(bg8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 680, 430));

        action_window8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bgWHITE.png"))); // NOI18N
        jPanel11.add(action_window8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1130, 510));

        javax.swing.GroupLayout cha_vac_frameLayout = new javax.swing.GroupLayout(cha_vac_frame.getContentPane());
        cha_vac_frame.getContentPane().setLayout(cha_vac_frameLayout);
        cha_vac_frameLayout.setHorizontalGroup(
            cha_vac_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        cha_vac_frameLayout.setVerticalGroup(
            cha_vac_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.add(cha_vac_frame, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1140, 540));

        bottom_banner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/banner_low.png"))); // NOI18N
        jPanel3.add(bottom_banner, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 600, 1140, 40));
        jPanel3.add(action_window, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1140, 550));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bg.png"))); // NOI18N
        jPanel3.add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1140, 640));

        testing_menu.setText("Testing");
        testing_menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                testing_menuMouseEntered(evt);
            }
        });

        cha_test.setText("Update Results");
        cha_test.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cha_testActionPerformed(evt);
            }
        });
        testing_menu.add(cha_test);

        covid_mgmnt_menu.add(testing_menu);

        vaccination_menu.setText("Vaccination");

        cha_vac.setText("Issue Certificates");
        cha_vac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cha_vacActionPerformed(evt);
            }
        });
        vaccination_menu.add(cha_vac);

        covid_mgmnt_menu.add(vaccination_menu);

        title_screen_menu.setText("Title Screen");
        title_screen_menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                title_screen_menuMouseClicked(evt);
            }
        });
        title_screen_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                title_screen_menuActionPerformed(evt);
            }
        });
        covid_mgmnt_menu.add(title_screen_menu);

        sign_out_menu.setText("Sign out");
        sign_out_menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sign_out_menuMouseClicked(evt);
            }
        });
        sign_out_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sign_out_menuActionPerformed(evt);
            }
        });
        covid_mgmnt_menu.add(sign_out_menu);

        exit_menu.setText("Exit");
        exit_menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit_menuMouseClicked(evt);
            }
        });
        exit_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_menuActionPerformed(evt);
            }
        });
        covid_mgmnt_menu.add(exit_menu);

        setJMenuBar(covid_mgmnt_menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void title_screen_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_title_screen_menuActionPerformed
        // TODO add your handling code here:
        MainAdmin ma = new MainAdmin();
        setVisible(false);
        ma.setVisible(true);
    }//GEN-LAST:event_title_screen_menuActionPerformed

    private void sign_out_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sign_out_menuActionPerformed
        // TODO add your handling code here:
        lab_login_page llp = new lab_login_page();
        super.setVisible(false);
        llp.setVisible(true);
    }//GEN-LAST:event_sign_out_menuActionPerformed

    private void exit_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_menuActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_exit_menuActionPerformed

    private void sign_out_menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sign_out_menuMouseClicked
        // TODO add your handling code here:
        user_login_page ma = new user_login_page();
	ma.setVisible(true);
	setVisible(false);
    }//GEN-LAST:event_sign_out_menuMouseClicked

    private void exit_menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit_menuMouseClicked
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_exit_menuMouseClicked

    private void title_screen_menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_title_screen_menuMouseClicked
        // TODO add your handling code here:
        MainAdmin ma = new MainAdmin();
	ma.setVisible(true);
	setVisible(false);
    }//GEN-LAST:event_title_screen_menuMouseClicked

    private void cha_testActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cha_testActionPerformed
        // TODO add your handling code here:
        cha_test_frame.setVisible(true);
    }//GEN-LAST:event_cha_testActionPerformed

    private void testing_menuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_testing_menuMouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_testing_menuMouseEntered

    private void cd_cha_testActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cd_cha_testActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cd_cha_testActionPerformed

    private void cc_cha_testActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cc_cha_testActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cc_cha_testActionPerformed

    private void labid_cha_testActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_labid_cha_testActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_labid_cha_testActionPerformed

    private void exit5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit5ActionPerformed
        // TODO add your handling code here:
        cha_test_frame.setVisible(false);
        labid_cha_test.setText("");
        cc_cha_test.setText("");
        cd_cha_test.setText("");
        nd_cha_test.setText("");
    }//GEN-LAST:event_exit5ActionPerformed
    
    
    private void nd_cha_testActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nd_cha_testActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nd_cha_testActionPerformed

    private void change_cha_testActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_change_cha_testActionPerformed
        // TODO add your handling code here:
        try
			    {
			      Class.forName("com.mysql.jdbc.Driver");
			      Connection conn = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/covid_management","root","2099");
			      PreparedStatement ps = conn.prepareStatement("UPDATE covid_management.testing SET result = ? WHERE labid = ?;");
			      ps.setString(1, nd_cha_test.getText());
                              ps.setString(2, labid_cha_test.getText());
			      int rs = ps.executeUpdate();
			      if (rs>0)
			      {
			        JOptionPane.showMessageDialog(null,"Result Uploaded!");
			      }
                              else{JOptionPane.showMessageDialog(null,"Sorry, Server Crashed.");}
			    }
			    catch (Exception e1)
			    {
			      System.err.println("Got an exception! ");
                              JOptionPane.showMessageDialog(null,"Error Occured!");
			      System.err.println(e1);
			    }
    }//GEN-LAST:event_change_cha_testActionPerformed

    private void search_cha_testActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_cha_testActionPerformed
        // TODO add your handling code here:
        try
			    {
			      Class.forName("com.mysql.jdbc.Driver");
			      Connection conn = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/covid_management","root","2099");
			      PreparedStatement ps = conn.prepareStatement("SELECT * FROM covid_management.testing where labid =?;");
			      ps.setString(1, labid_cha_test.getText());
			      ResultSet rs = ps.executeQuery();
			      if (rs.next()==true)
			      {
			        String resx = rs.getString("result");
                                PreparedStatement es = conn.prepareStatement("SELECT * FROM covid_management.lablogin where labid =?;");
                                es.setString(1, labid_cha_test.getText());
                                ResultSet xs = es.executeQuery();
                                if (xs.next()==true){
                                    String loca = xs.getString("lablocation");
                                    cc_cha_test.setText(loca);
                                }
			        cd_cha_test.setText(resx);
			      }
			    }
			    catch (Exception e1)
			    {
			      System.err.println("Got an exception! ");
			      System.err.println(e1);
			    }
    }//GEN-LAST:event_search_cha_testActionPerformed

    private void cha_vacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cha_vacActionPerformed
        // TODO add your handling code here:
        cha_vac_frame.setVisible(true);
    }//GEN-LAST:event_cha_vacActionPerformed

    private void change_cha_test2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_change_cha_test2ActionPerformed
        // TODO add your handling code here:
        try
			    {
			      Class.forName("com.mysql.jdbc.Driver");
			      Connection conn = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/covid_management","root","2099");
			      PreparedStatement ps = conn.prepareStatement("UPDATE covid_management.vaccination SET result = ? WHERE labid = ?;");
			      ps.setString(1, nd_cha_vac.getText());
                              ps.setString(2, labid_cha_vac.getText());
			      int rs = ps.executeUpdate();
			      if (rs>0)
			      {
			        JOptionPane.showMessageDialog(null,"Result Uploaded!");
			      }
                              else{JOptionPane.showMessageDialog(null,"Sorry, Server Crashed.");}
			    }
			    catch (Exception e1)
			    {
			      System.err.println("Got an exception! ");
                              JOptionPane.showMessageDialog(null,"Error Occured!");
			      System.err.println(e1);
			    }
    }//GEN-LAST:event_change_cha_test2ActionPerformed

    private void nd_cha_vacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nd_cha_vacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nd_cha_vacActionPerformed

    private void search_cha_test2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_cha_test2ActionPerformed
        // TODO add your handling code here:
        try
			    {
			      Class.forName("com.mysql.jdbc.Driver");
			      Connection conn = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/covid_management","root","2099");
			      PreparedStatement ps = conn.prepareStatement("SELECT * FROM covid_management.vaccination where labid =?;");
			      ps.setString(1, labid_cha_vac.getText());
			      ResultSet rs = ps.executeQuery();
			      if (rs.next()==true)
			      {
			        String resx = rs.getString("result");
                                PreparedStatement es = conn.prepareStatement("SELECT * FROM covid_management.lablogin where labid =?;");
                                es.setString(1, labid_cha_vac.getText());
                                ResultSet xs = es.executeQuery();
                                if (xs.next()==true){
                                    String loca = xs.getString("lablocation");
                                    cc_cha_vac.setText(loca);
                                }
			        cd_cha_vac.setText(resx);
			      }
			    }
			    catch (Exception e1)
			    {
			      System.err.println("Got an exception! ");
			      System.err.println(e1);
			    }
    }//GEN-LAST:event_search_cha_test2ActionPerformed

    private void cd_cha_vacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cd_cha_vacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cd_cha_vacActionPerformed

    private void cc_cha_vacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cc_cha_vacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cc_cha_vacActionPerformed

    private void labid_cha_vacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_labid_cha_vacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_labid_cha_vacActionPerformed

    private void exit7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit7ActionPerformed
        // TODO add your handling code here:
        cha_vac_frame.setVisible(false);
        labid_cha_vac.setText("");
        cc_cha_vac.setText("");
        cd_cha_vac.setText("");
        nd_cha_vac.setText("");
    }//GEN-LAST:event_exit7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(user_loggedin_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(user_loggedin_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(user_loggedin_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(user_loggedin_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new lab_loggedin_page().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel action_window;
    private javax.swing.JLabel action_window6;
    private javax.swing.JLabel action_window8;
    private javax.swing.JLabel bg;
    private javax.swing.JLabel bg6;
    private javax.swing.JLabel bg8;
    private javax.swing.JLabel bottom_banner;
    private javax.swing.JTextField cc_cha_test;
    private javax.swing.JTextField cc_cha_vac;
    private javax.swing.JTextField cd_cha_test;
    private javax.swing.JTextField cd_cha_vac;
    private javax.swing.JMenuItem cha_test;
    private javax.swing.JInternalFrame cha_test_frame;
    private javax.swing.JMenuItem cha_vac;
    private javax.swing.JInternalFrame cha_vac_frame;
    private javax.swing.JButton change_cha_test;
    private javax.swing.JButton change_cha_test2;
    private javax.swing.JMenuBar covid_mgmnt_menu;
    private javax.swing.JButton exit5;
    private javax.swing.JButton exit7;
    private javax.swing.JMenu exit_menu;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField labid_cha_test;
    private javax.swing.JTextField labid_cha_vac;
    private javax.swing.JTextField nd_cha_test;
    private javax.swing.JTextField nd_cha_vac;
    private javax.swing.JLabel password_label5;
    private javax.swing.JLabel password_label7;
    private javax.swing.JLabel phone_label11;
    private javax.swing.JLabel phone_label13;
    private javax.swing.JLabel phone_label14;
    private javax.swing.JLabel phone_label15;
    private javax.swing.JButton search_cha_test;
    private javax.swing.JButton search_cha_test2;
    private javax.swing.JMenu sign_out_menu;
    private javax.swing.JMenu testing_menu;
    private javax.swing.JLabel title_banner;
    private javax.swing.JMenu title_screen_menu;
    private javax.swing.JLabel username_label10;
    private javax.swing.JLabel username_label11;
    private javax.swing.JLabel username_label14;
    private javax.swing.JLabel username_label15;
    private javax.swing.JMenu vaccination_menu;
    // End of variables declaration//GEN-END:variables

    
}
