
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.*;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author fola
 */
public class MainAdmin extends javax.swing.JFrame {

    /**
     * Creates new form MainAdmin
     */
     Connection conn = null;
    Statement stmt = null;
    ResultSet rs = null;
    
    public MainAdmin() {
       super("Admin Login");
        initComponents();
        conn = dbaseConnx.openConnection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        title_banner = new javax.swing.JLabel();
        bottom_banner = new javax.swing.JLabel();
        banner_slideshow = new javax.swing.JLabel();
        exit_btn = new javax.swing.JButton();
        user_login = new javax.swing.JButton();
        lab_login = new javax.swing.JButton();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Welcome to Covid Manager!");
        setBackground(new java.awt.Color(241, 241, 241));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title_banner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/title_banner.png"))); // NOI18N
        jPanel3.add(title_banner, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1140, 50));

        bottom_banner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/banner_low.png"))); // NOI18N
        jPanel3.add(bottom_banner, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 600, 1140, 40));

        banner_slideshow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/banner_slideshow_2.gif"))); // NOI18N
        jPanel3.add(banner_slideshow, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1140, 340));

        exit_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit_btn.png"))); // NOI18N
        exit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_btnActionPerformed(evt);
            }
        });
        jPanel3.add(exit_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 520, 180, 40));

        user_login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user_login.png"))); // NOI18N
        user_login.setToolTipText("");
        user_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_loginActionPerformed(evt);
            }
        });
        jPanel3.add(user_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 470, 180, 40));

        lab_login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lab_login.png"))); // NOI18N
        lab_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lab_loginActionPerformed(evt);
            }
        });
        jPanel3.add(lab_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 470, 180, 40));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bg.png"))); // NOI18N
        jPanel3.add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1140, 640));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void user_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_loginActionPerformed
        // TODO add your handling code here:
        user_login_page ulp = new user_login_page();
	ulp.setVisible(true);
	setVisible(false);
    }//GEN-LAST:event_user_loginActionPerformed

    private void lab_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lab_loginActionPerformed
        // TODO add your handling code here:
        lab_login_page llp = new lab_login_page();
	llp.setVisible(true);
	setVisible(false);
    }//GEN-LAST:event_lab_loginActionPerformed

    private void exit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_btnActionPerformed
        // TODO add your handling code here:
	setVisible(false);
    }//GEN-LAST:event_exit_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel banner_slideshow;
    private javax.swing.JLabel bg;
    private javax.swing.JLabel bottom_banner;
    private javax.swing.JButton exit_btn;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton lab_login;
    private javax.swing.JLabel title_banner;
    private javax.swing.JButton user_login;
    // End of variables declaration//GEN-END:variables
}
