import java.awt.*;
import javax.swing.*;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.proteanit.sql.DbUtils;
import java.text.ParseException;

/**
 *
 * @author larry
 */
public class user_signup_page extends javax.swing.JFrame {

    /**
     * Creates new form user_signup_page
     */
    //Connection conn = null;
    //Statement stmt = null;
    //ResultSet rs = null;
    public user_signup_page() {
      super("Sign up Page");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        username_label2 = new javax.swing.JLabel();
        back_btn = new javax.swing.JButton();
        phone = new javax.swing.JTextField();
        age_label = new javax.swing.JLabel();
        password = new javax.swing.JTextField();
        age = new javax.swing.JTextField();
        phone_label = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        password_label = new javax.swing.JLabel();
        username_label = new javax.swing.JLabel();
        action_window2 = new javax.swing.JLabel();
        user_login_heading = new javax.swing.JLabel();
        login_btn = new javax.swing.JButton();
        bottom_banner = new javax.swing.JLabel();
        title_banner = new javax.swing.JLabel();
        action_window = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Welcome to Covid Manager ");

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        username_label2.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        username_label2.setForeground(new java.awt.Color(46, 56, 80));
        username_label2.setText("Enter New User Details,");
        jPanel3.add(username_label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 90, 250, 50));

        back_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back_btn.png"))); // NOI18N
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });
        jPanel3.add(back_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 540, 180, 40));

        phone.setBackground(new java.awt.Color(242, 242, 242));
        phone.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        phone.setForeground(new java.awt.Color(46, 56, 80));
        phone.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        phone.setToolTipText("Please enter correct Username");
        phone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneActionPerformed(evt);
            }
        });
        jPanel3.add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 400, 370, 40));

        age_label.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        age_label.setForeground(new java.awt.Color(46, 56, 80));
        age_label.setText("Age:");
        jPanel3.add(age_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, 130, 50));

        password.setBackground(new java.awt.Color(242, 242, 242));
        password.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        password.setForeground(new java.awt.Color(46, 56, 80));
        password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        password.setToolTipText("Please enter correct Username");
        password.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        jPanel3.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 250, 370, 40));

        age.setBackground(new java.awt.Color(242, 242, 242));
        age.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        age.setForeground(new java.awt.Color(46, 56, 80));
        age.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        age.setToolTipText("Please enter correct Username");
        age.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageActionPerformed(evt);
            }
        });
        jPanel3.add(age, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 320, 370, 40));

        phone_label.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        phone_label.setForeground(new java.awt.Color(46, 56, 80));
        phone_label.setText("Phone No:");
        jPanel3.add(phone_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 400, 120, 50));

        username.setBackground(new java.awt.Color(242, 242, 242));
        username.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        username.setForeground(new java.awt.Color(46, 56, 80));
        username.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        username.setToolTipText("Please enter correct Username");
        username.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        jPanel3.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 170, 370, 40));

        password_label.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        password_label.setForeground(new java.awt.Color(46, 56, 80));
        password_label.setText("Password :");
        jPanel3.add(password_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, 120, 50));

        username_label.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        username_label.setForeground(new java.awt.Color(46, 56, 80));
        username_label.setText("Username : ");
        jPanel3.add(username_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 130, 50));

        action_window2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bg.png"))); // NOI18N
        jPanel3.add(action_window2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 630, 360));

        user_login_heading.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/signup_heading.png"))); // NOI18N
        jPanel3.add(user_login_heading, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 240, 50));

        login_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/signup_btn.png"))); // NOI18N
        login_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_btnActionPerformed(evt);
            }
        });
        jPanel3.add(login_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 540, 180, 40));

        bottom_banner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/banner_low.png"))); // NOI18N
        jPanel3.add(bottom_banner, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 600, 1140, 40));

        title_banner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/title_banner.png"))); // NOI18N
        jPanel3.add(title_banner, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1140, 50));

        action_window.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bgWHITE.png"))); // NOI18N
        jPanel3.add(action_window, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1140, 550));
        jPanel3.add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1140, 640));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void login_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_btnActionPerformed
        try {
                    if(!(phone.getText().equals("") && username.getText().equals("") && age.getText().equals("") && password.getText().equals(""))){
                            String phone_s = phone.getText();
                            if(phone_s.length()!=10)
                                    JOptionPane.showMessageDialog(null,"Invalid Phone number");
                            int ageint;
                            ageint = Integer.parseInt(age.getText());
                            Class.forName("com.mysql.jdbc.Driver");
                            Connection conn = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/covid_management","root","2099");
                            if(ageint >= 18) {
                                    PreparedStatement ps = conn.prepareStatement("insert into covid_management.signup(phno,name,age,password) values (?,?,?,?);");
                                    ps.setString(1, phone.getText());
                                    ps.setString(2, username.getText());
                                    ps.setString(3, age.getText());
                                    ps.setString(4, password.getText());
                                    int x = ps.executeUpdate();
                                    if(x>0) {
                                            JOptionPane.showMessageDialog(null,"SignUp sucessfull!!");
                                            user_login_page ulp = new user_login_page();
                                            ulp.setVisible(true);
                                            setVisible(false);
                                    } else {JOptionPane.showMessageDialog(null,"SignUp unsucessfull!!");}
                            } else {JOptionPane.showMessageDialog(null,"SignUp requires age to be above 18.");}
                    } else {JOptionPane.showMessageDialog(null,"Please enter all the fields.");}
        } catch(Exception e1) {JOptionPane.showMessageDialog(null,"Duplicate entry or all the fields have not been entered.");}
    }//GEN-LAST:event_login_btnActionPerformed

    private void ageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneActionPerformed

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        // TODO add your handling code here:
        user_login_page ma = new user_login_page();
        ma.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_back_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(user_signup_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(user_signup_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(user_signup_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(user_signup_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new user_signup_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel action_window;
    private javax.swing.JLabel action_window2;
    private javax.swing.JTextField age;
    private javax.swing.JLabel age_label;
    private javax.swing.JButton back_btn;
    private javax.swing.JLabel bg;
    private javax.swing.JLabel bottom_banner;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton login_btn;
    private javax.swing.JTextField password;
    private javax.swing.JLabel password_label;
    private javax.swing.JTextField phone;
    private javax.swing.JLabel phone_label;
    private javax.swing.JLabel title_banner;
    private javax.swing.JLabel user_login_heading;
    private javax.swing.JTextField username;
    private javax.swing.JLabel username_label;
    private javax.swing.JLabel username_label2;
    // End of variables declaration//GEN-END:variables
}
